import Link from 'next/link'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Thailand Endurance Cup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.nav}>
          <ul>
            <li><Link href="/posts/first-post"><a>Home</a></Link></li>
            <li><Link href="/posts/first-post"><a>Mappool</a></Link></li>
            <li><Link href="/posts/first-post"><a>Registration</a></Link></li>
            <li><Link href="/posts/first-post"><a>Bracket</a></Link></li>
            </ul>
        </h2>

        <h1 className={styles.body}>
        <p>
          <Image src="/239189.jpg" alt="Something" width={200} height={200} />
          Thailand Endurance Cup
          </p>
        <p>
          Season 2
          </p>
        </h1>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
